apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location
  name: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  strategy: {}
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
      - image: location
        name: location
        ports:
        - containerPort: 33001
        - containerPort: 3300
        resources: {}
      - image: mongo
        name: mongo
        ports:
        - containerPort: 33001
        - containerPort: 3300
        resources: {}
status: {}
