apiVersion: v1
kind: Pod
metadata:
  labels:
    run: locationdb
  name: locationdb
spec:
  containers:
  - image: bitnami/mongodb
    name: locationdb
    envFrom:
    - secretRef:
        name: location-db-secret
    ports:
    - containerPort: 27017
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
