apiVersion: v1
kind: Service
metadata:
  labels:
    app: locationapp
  name: locationapp
spec:
  type: NodePort
  ports:
  - port: 30001
    name: locationapp
    protocol: TCP
    targetPort: 30001
    nodePort: 30001
  - port: 30002
    name: locationapp-grpc
    protocol: TCP
    targetPort: 30002
    nodePort: 30002
  selector:
    app: locationapp
status:
  loadBalancer: {}
