apiVersion: v1
kind: Service
metadata:
  labels:
    run: locationdb
  name: locationdb
spec:
  ports:
  - port: 31001
    protocol: TCP
    targetPort: 27017
  selector:
    run: locationdb
status:
  loadBalancer: {}
